### ISSUE TITLE
Please, add to the readme a note about installation from Ultralisp?

### ISSUE THREAD

**Issue by svetlyak40wt** [julian-baldwin/parachute-browser#1]
Hi, Julian!

I've added this project to Ultralisp: https://ultralisp.org/projects/julian-baldwin/parachute-browser

Now it can be installed using the quicklisp client.

**Comment by julian-baldwin** [comment]
Done, thanks for adding it as it didn't occur to me! I've implemented a basic 'find test source' feature too.
